### PR TITLE
Adding uniqueId-ification to masks/paths in main component

### PR DESCRIPTION
**Pull request by cgross**
It looks like effort was made to ensure masks and path elements would have unique ids in the various pieces.  But that same effort wasn't done in the main Avatar class.  In our app, this caused the avatars to disappear if the first avatar on the page was destroyed or hidden (assumedly because all the avatars were reusing the masks/paths from that initial svg).  

The diff is quite noisy because I think I compiled it with a newer version of typescript (not sure though, I'm not a heavy typescript user).  All of my changes were isolated in `src/avatar/index.tsx`.

### CODE REVIEW

**Comment by cgross** [comment]
Hi Maintainers!

Kindly request you look at and merge this PR.  The current codebase has a bug where different svgs with the same ID are being removed by the browser and messing up any other avatars that may use components with the same ID.  Essentially this makes the library only useful if one avatar is shown at the same time (or if avatars are never removed from the DOM).  This PR fixes those issues.

**Comment by soulteary** [comment]
Thank you for @cgross submitting. I checked the latest code and found that referring to your code has corrected this problem.

**Comment by lancejpollard** [comment]
@cgross please fix the merge conflicts if you get a chance, I think it will fix this issue of rendering multiple avatars on a single page getting all jumbled up 😅 .

Screen Shot 2021-08-14 at 7 26 35 AM

**Comment by fangpenlin** [comment]
Hi @cgross, sorry I was super busy until recent have a bit time to look into these. Do you mind fixing the conflicts in this PR? So that I can merge it. I just hope the original contributor can get their credit. I can also create a new PR with your change myself to address the conflicts, and then add your name into a contributors list to thank you for making this PR.

**Comment by cgross** [comment]
@fangpenlin I'm busy myself but definitely not worried about getting created.  Feel free to make a new PR with my changes.  Glad to get this issue knocked out.  We've been maintaining a forked copy due to this bug.

**Comment by fangpenlin** [comment]
https://github.com/fangpenlin/avataaars/commit/b306029c6316593757e0100356155b77be4a956e seems like I have already brought your changes into the code a while back. thank you so much for the PR, closing this now

**Pull request closed without merging**
